### ISSUE TITLE
generated bandwidth seems incorrect

### ISSUE THREAD

**Issue by J-Rogmann** [maxsharabayko/srt-xtransmit#3]
srt-xtransmit was used to generate a 7 Mbps stream (on a link with 4% data loss)
However, the data analysis with [lib-tcpdump-processing](https://github.com/mbakholdina/lib-tcpdump-processing) showed values way off 7 Mbps.

```
./srt-xtransmit generate "srt://192.168.2.2:4200&latency=100" \
--msgsize 1316 -v --sendrate 7Mbps --duration 30s
```

```
SRT Data payload:          6.665 Mbps
SRT Data overhead:         1.824%
SRT Data lost:             0.000%
SRT Data rexmit overhead:  10.723%
SRT ACK overhead:          0.286%
SRT ACKACK overhead:       0.286%
SRT NAK overhead:          0.162%
===========================================
SRT overall overhead:      11.325%
SRT Retransmitted:         10.531% of original packets
including:
    retransmitted twice:   0.291% of original packets
    retransmitted more:    3.304% of original packets
```
Data Payload + Data overhead sums up to 6.7866 Mbps

An additional between flip & flop (no packet loss) showed following using iptraf-ng

`Incoming rates:    7256.78 kbps`
which is devided by 1024:
`Incoming rates:    7.0867 Mbps`

Maybe I got a misunderstanding of what the rates out of the lib-tcpdump-processing mean, but the difference is quite large.

**Comment by maxsharabayko** [comment]
Checked without losses. Works pretty well. 🤔 
```
Overall UDP rate:          7.111 Mbps
SRT Data org+rexmit pld:   6.984 Mbps
SRT Data org payload:      6.984 Mbps
```
