### ISSUE TITLE
[Question] Why is the actual sending/receiving rate so much lower than the estimated bandwidth?

### ISSUE THREAD

**Issue by nrecker-atlas** [maxsharabayko/srt-xtransmit#51]
Howdy,

I'm trying to use srt-xtransmit to see how fast I can send data via srt. When I do, I get actual sending and receiving rates around ~1100 mbps, but the estimated bandwidth is around ~3000 mbps. Via iperf3, I get ~4300 mbps. Why is the actual rate so much lower than the estimated bandwidth? Is there anything I can/should do to raise the actual rate to meet/approach the available bandwidth?

From file mode:
![srt_plot](https://user-images.githubusercontent.com/107578651/178557821-9c655852-4ab7-4ea9-abe2-3e1c9ae7bb86.png)

Here are the commands I used (IPs redacted). It's just the defaults recommended by the README but with --sendrate set to 1200mbps for live mode and --num set to 10,000,000 instead of 1000 for file mode.

Live mode:
Sender: `srt-xtransmit generate "srt://<ip>:<port>?transtype=live&rcvbuf=1000000000&sndbuf=1000000000" --msgsize 1316 --sendrate 1200Mbps --duration 10s --statsfile stats-snd.csv --statsfreq 100ms`
Receiver: `srt-xtransmit receive "srt://:<port>?transtype=live&rcvbuf=1000000000&sndbuf=1000000000" --msgsize 1316 --statsfile stats-rcv.csv --statsfreq 100ms`

File mode:
Sender: `./srt-xtransmit generate "srt://<ip>:<port>?transtype=file&messageapi=1&payloadsize=1456&rcvbuf=1000000000&sndbuf=1000000000&fc=800000" --msgsize 1456 --num 10000000 --statsfile stats-snd.csv --statsfreq 1s`
Receiver: `./srt-xtransmit receive "srt://:<port>?transtype=file&messageapi=1&payloadsize=1456&rcvbuf=1000000000&sndbuf=1000000000&fc=800000" --msgsize 1456  --statsfile stats-rcv.csv --statsfreq 1s`

Here are all the stats files:
[stats-rcv_1200mbps.csv](https://github.com/maxsharabayko/srt-xtransmit/files/9095485/stats-rcv_1200mbps.csv)
[stats-snd_1200mbps.csv](https://github.com/maxsharabayko/srt-xtransmit/files/9095487/stats-snd_1200mbps.csv)
[stats-rcvFile10M.csv](https://github.com/maxsharabayko/srt-xtransmit/files/9095489/stats-rcvFile10M.csv)
[stats-sndFile10M.csv](https://github.com/maxsharabayko/srt-xtransmit/files/9095492/stats-sndFile10M.csv)

**Comment by nrecker-atlas** [comment]
I tried running the same command (live mode) on the same machine across localhost, which should have more than enough bandwidth (iperf3 tells me 19.2 gbps). Yet the actual throughput is about the same, close to 1Gbps.
What could be causing dropped packets if not connection speed, and how might I fix/improve it?

![stats-rcv_localhost_live1200](https://user-images.githubusercontent.com/107578651/181096793-5d366a6b-7c11-4dc8-8b15-8fa8a6e0cf04.png)

stats files:
[stats-rcv_localhost_1200mbps.csv](https://github.com/maxsharabayko/srt-xtransmit/files/9192834/stats-rcv_localhost_1200mbps.csv)
[stats-snd_localhost_1200mbps.csv](https://github.com/maxsharabayko/srt-xtransmit/files/9192836/stats-snd_localhost_1200mbps.csv)

**Comment by maxsharabayko** [comment]
May be related to the pacing accuracy. By default SRT uses system timers to wait for the next packet to be sent. System timers are not that accurate, especially on Windows, which may lead to higher sending rates at some short interval. For example, if you collect stats with 100 ms frequency, you might see the sending rate exceeding the average.
At that high bitrates you can increase the accuracy by building with [USE_BUSY_WAITING](https://github.com/Haivision/srt/blob/master/docs/build/build-options.md#use_busy_waiting) build option. In this case, SRT will pace sending using [spin wait](https://github.com/Haivision/srt/blob/master/srtcore/sync.cpp#L190) (loop until target time) instead of timers.

**Comment by nrecker-atlas** [comment]
I tried compiling the srt submodule with --use-busy-waiting and running again on localhost.
It still only gets about 1gbps.

Graph:
![stats-rcv_busywait_localhost_live1200_nospinwait](https://user-images.githubusercontent.com/107578651/181360288-8ab77a57-f48c-41d6-979f-534a7c58646f.png)


Graph with also using the --spin-wait flag for srt-xtransmit generate:
![stats-rcv_busywait_localhost_live1200](https://user-images.githubusercontent.com/107578651/181360305-e365f550-0895-4023-8b1a-5cf07fecd054.png)

[stats-rcv_localhost_busywait_live1200.csv](https://github.com/maxsharabayko/srt-xtransmit/files/9203175/stats-rcv_localhost_busywait_live1200.csv)
[stats-rcv_localhost_busywait_nospinwait_live1200.csv](https://github.com/maxsharabayko/srt-xtransmit/files/9203176/stats-rcv_localhost_busywait_nospinwait_live1200.csv)

**Comment by maxsharabayko** [comment]
Interestingly there are no retransmitted or belated packets on the receiver side. Those packets above 1Gbps just don't reach the receiver for some reason. Maybe that is the actual sustainable throughput on a local host.

You can also try performing the same experiment, but using UDP instead of SRT.

```shell
(sender)
srt-xtransmit generate "udp://<ip>:<port>" --msgsize 1316 --sendrate 1200Mbps --duration 10s --enable-metrics

(receiver)
srt-xtransmit receive "udp://:<port>" --enable-metrics --metricsfile udp-rcv-metrics.csv --metricsfreq 100ms
```

Then you can use the file to plot xtransmit metrics with the [plot_metrics.py](https://github.com/maxsharabayko/srt-xtransmit/blob/master/scripts/plot_metrics.py) script.

**Comment by nrecker-atlas** [comment]
Xtransmit with udp also drops packets.

![udp-rcv-metrics_live1200](https://user-images.githubusercontent.com/107578651/181774252-4d198341-3b9e-400d-96c9-123ae9ec86c8.png)

Using iperf3 -u -b 1200000000 to test udp gives similar results; 4.3% of packets dropped at a 1200mbps send rate.
This is despite iperf3 using TCP sending 18.5gbps with 0 retransmits.
I've often heard that udp and srt are better suited to high throughput than tcp, so this surprises me.

**Comment by maxsharabayko** [comment]
Well, some networks are aware that UDP is unreliable and can be dropped while dropping a TCP packet would likely lead to retransmission. Therefore they raise the priority of the TCP traffic over UDP.
TCP suffers from a head of line blocking, the delivery time is not guaranteed. Detecting and retransmitting a loss is also quite painful for TCP.
Also if you are running tests on a localhost, the results might be different from those you get on a real network.

TCP sending can also be checked with the [BWChecker](https://github.com/maxsharabayko/bwcheck).
Have to add TCP to the xtransmit [some day](https://github.com/maxsharabayko/srt-xtransmit/pull/45).

**Comment by nrecker-atlas** [comment]
I tried BWChecker, and it seems its tcp mode only sends a single message, rather than testing throughput.
![bwchecker_tcp](https://user-images.githubusercontent.com/107578651/182199395-0a243d76-5b38-4c0a-b334-3321117a0173.png)

**Comment by maxsharabayko** [comment]
Ah, ok. I have not implemented that for TCP then. Sorry :)
