### ISSUE TITLE
Socket groups: invalid URI query option

### ISSUE THREAD

**Issue by nrecker-atlas** [maxsharabayko/srt-xtransmit#53]
I'm having some trouble getting socket groups working. Following the instructions at https://github.com/maxsharabayko/srt-xtransmit/blob/master/docs/socket-groups.md, I compiled with -DENABLE_BONDING=ON. When I run the provided example generate command for multiple ports:

`./srt-xtransmit generate srt://127.0.0.1:55555?grouptype=backup&weight=2 srt://127.0.0.1:55556?weight=1 --enable-metrics --reconnect`

I get the following output, whether or not the corresponding receive command is running:

`[1] 2085
-bash: srt://127.0.0.1:55556?weight=1: No such file or directory`
`14:56:47.531200 [W] CONN Invalid URI query option`
`'grouptype=backup (not recognized)!`

**Comment by maxsharabayko** [comment]
The `&` symbol can be interpreted by the shell as a command to run the following part in the background as a separate command.

Try with `"`:
`./srt-xtransmit generate "srt://127.0.0.1:55555?grouptype=backup&weight=2" "srt://127.0.0.1:55556?weight=1" --enable-metrics --reconnect`

**Comment by nrecker-atlas** [comment]
Ah! Thank you
