### ISSUE TITLE
Create stable release for package managers

### ISSUE THREAD

**Issue by nt74** [maxsharabayko/srt-xtransmit#94]
Is it possible to create stable releases for package managers (like myself) that are updated in-sync with Git-pushes?

**Comment by maxsharabayko** [comment]
Do you mean a release for every git push or do releases more often?

**Comment by nt74** [comment]
Do releases more often. The most "stable" ones at least.

**Comment by maxsharabayko** [comment]
Release [v0.2.0](https://github.com/maxsharabayko/srt-xtransmit/releases/tag/v0.2.0) is out. I will do releases more often depending on the activity in commits.
